name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
  
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Gabriel-Avelino/snk@main
        id: snake-gif
        with:
          github_user_name: Gabriel-Avelino
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: Gabriel-Avelino/ghaction-github-pages@dev
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Certifique-se de que o nome do secret seja consistente
